server.port=8080
debug=true
spring.security.oauth2.client.registration.client.client-id=client
spring.security.oauth2.client.registration.client.client-secret=H3aRydIrSL4ZM0E
spring.security.oauth2.client.registration.client.scope=openid
spring.security.oauth2.client.registration.client.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.client.redirect-uri=http://localhost:8080/login/oauth2/code/client

spring.security.oauth2.client.provider.client.authorization-uri=http://localhost/blitz/oauth/ae
spring.security.oauth2.client.provider.client.token-uri=http://localhost/blitz/oauth/re