server.port=8081

spring.security.oauth2.client.registration.oauth2-demo-thymeleaf-client.client-id=gateway
spring.security.oauth2.client.registration.oauth2-demo-thymeleaf-client.client-secret=zn5olSzjysNQTTB4NbY0F8W8pkHbPnrn
spring.security.oauth2.client.registration.oauth2-demo-thymeleaf-client.scope=openid, profile, roles
spring.security.oauth2.client.registration.oauth2-demo-thymeleaf-client.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.oauth2-demo-thymeleaf-client.redirect-uri=http://localhost:8081/login/oauth2/code/oauth2-demo-thymeleaf-client

spring.security.oauth2.client.provider.oauth2-demo-thymeleaf-client.issuer-uri=http://localhost:8080/auth/realms/keycloak